title: spanishgum
description: Hi, I'm Adam! I like computer sciences, mathematics, music, food, and good people.
show_downloads: false
google_analytics: UA-98750502-1
theme: jekyll-theme-hacker
facebook: aps10d
twitter: spanishgum
linkedin: adam-stallard-4351b76a/
google: u/0/+AdamStallard
instagram: spanishgum
reddit: spanishgum
ycombinator: spanishgum
stackoverflow: 3454650/spanishgum
tumblr: spanishgum
soundcloud: adam-preston-stallard
spotify: 1266112379
default_jsheadarr:
  - d3.min.js
default_jsfootarr:
  - jquery.tipsy.js
  - graph.js
jsheadarr:
  - jquery.min.js
jsfootarr:
  - toggle.js
gems:
  - jekyll-seo-tag
