title: spanishgum
description: Hi, I'm Adam! I like computer sciences, mathematics, music, food, and good people.
show_downloads: false
google_analytics: false
theme: jekyll-theme-hacker
facebook: aps10d
twitter: spanishgum
linkedin: adam-stallard-4351b76a/
google: u/0/+AdamStallard
instagram: spanishgum
reddit: spanishgum
ycombinator: spanishgum
tumblr: spanishgum
soundcloud: adam-preston-stallard
jsheadarr:
- jquery.min.js
- d3.min.js
jsfootarr:
- jquery.tipsy.js
- graph.js
